### PR TITLE
Stowable trait

### LINKED ISSUE #8: small uninitialized types are unsound
Similar to #3, but it can't be fixed by zeroing beforehand

```rust
struct Thing(MaybeUninit<usize>);
fn main() {
    assert_eq!(size_of::<Thing>(), size_of::<*mut Thing>());
    let thing = Thing(MaybeUninit::uninit());
    let stowed = Stowaway::new(thing); // miri fails here, encountered uninitialized bytes
}
```

### PR DESCRIPTION
**Pull request by Lucretiel**
- Addded unsafe trait Stowable, which asserts that a type has no uninit bytes
- Implemented Stowable for several built-in types- pointers, arrays, primitives
- Removed several TODO comments after validating correct behavior

Fixes #8 

@KrishnaSannasi

### CODE REVIEW

File: src/lib.rs [hunk 1]
```diff
@@ -134,13 +137,130 @@
...
+///
+/// Correct usage of this trait is critical to stowaway's safety guarantees.
+/// This struct can only be implemented with MUST_BOX == false for types that
+/// can never have uninitialized bytes *anywhere* in their representation
+/// (including padding bytes).
+pub unsafe trait Stowable: Sized {
+    /// For objects with padding bytes or other uninitialized bytes that you
+    /// still want to use with stowaway, set this to true. It *is* safe to
+    /// implement `Stowable` for *any* type if MUST_BOX is true.
+    const MUST_BOX: bool = false;
```
Comment (RustyYato) [inline src/lib.rs]: I don't see the point in `MUST_BOX`, let's simplify the `unsafe` obligations to "the type must either be larger than a pointer, must be more aligned than a pointer, or must not contain *any* uninit bytes". You can document the case where using a `Stowaway<Box<T>>` won't do an extra allocation, so if a type does contain any uninit bytes it can be boxed at no extra cost.

(I'm trying to make it simpler to reason about `Stowable` so that it is easier to verify the correctness of this crate).

File: src/lib.rs [hunk 2]
```diff
@@ -134,13 +137,130 @@
...
+    Rc<T> Option<Rc<T>>
+    RcWeak<T> Option<RcWeak<T>>
+    NonNull<T> Option<NonNull<T>>
+}
+
+/// Implement stowable for array types. This is sounds because all types have
+/// a size that is a multiple of their alignment, so there's no type that is
+/// stowable but an array is not stowable.
+// TODO: use rustversion to opt-in to const generics if this is a nightly build
+macro_rules! stowable_array {
```
Comment (RustyYato) [inline src/lib.rs:231]: Maybe a nightly version of this crate can use const-generics to get all array impls? Not necessary, but it may be nicer.

File: src/lib.rs [hunk 3]
```diff
@@ -134,13 +137,130 @@
...
+// Stowaway instances are raw pointers. If T is MUST_BOX, then Stowaway<T>
+// contains a boxed instance of T, which means it is still safe to stow.
+unsafe impl<T: Stowable> Stowable for Stowaway<T> {}
+
+// Pointers are obviously safe to stow. References are technically safe to
+// stow; the user must ensure that the lifetimes are correctly reconstructed
+// when calling from_raw.
+unsafe impl<T> Stowable for *const T {}
+unsafe impl<T> Stowable for *mut T {}
+unsafe impl<T> Stowable for &T {}
```
Comment (RustyYato) [inline src/lib.rs]: Where's `&mut T`, `Option<&T>`, and `Option<&mut T>`?

File: src/lib.rs [hunk 4]
```diff
@@ -134,13 +137,130 @@
...
+
+/// Zero-size types are always fine
+unsafe impl Stowable for () {}
+
+/// Vec is always (ptr, size, cap)
+unsafe impl<T> Stowable for Vec<T> {}
```
Comment (RustyYato) [inline src/lib.rs:262]: Also a `Vec<_>` is always bigger than a `usize`, so it can't be stored inline.

File: src/lib.rs [hunk 5]
```diff
@@ -134,13 +137,130 @@
...
+
+/// MaybeUninit can obviously contain uninit bytes
+unsafe impl<T> Stowable for MaybeUninit<T> {
```
Comment (RustyYato) [inline src/lib.rs]: As per the first comment, `MaybeUninit<T>` shouldn't implement `Stowable`, if users want to use it, then they must first allocate their type using one of `Box<_>`, `Rc<_>`, or `Arc<_>`. This can be documented.

File: src/lib.rs [hunk 6]
```diff
@@ -173,28 +293,17 @@ use SizeClass::*;
 // TODO: Find a way to test that this actually does what it claims; that is,
 // that it boxes large values and copies small ones.
 #[repr(transparent)]
-pub struct Stowaway<T> {
-    // TODO: Reimplemnt this as union, once we can have non-copy fields in a
+pub struct Stowaway<T: Stowable> {
+    // TODO: Reimplement this as union, once we can have non-copy fields in a
```
Comment (RustyYato) [inline src/lib.rs:301]: You can't use a union here, I assume you want
```
union Stowable<T: Stowable> {
    ptr: *mut T,
    value: T,
}
```
But this would make `Stowable` the same size as `T` when `sizeof(T) > sizeof(ptr)`, which is not what we want.

File: src/lib.rs [hunk 7]
```diff
@@ -173,28 +293,17 @@ use SizeClass::*;
...
-        assert_eq!(
-            mem::size_of::<*mut T>(),
-            mem::size_of::<*mut ()>(),
-            "Cannot currently stow pointers to DSTs"
-        );
-
-        if mem::align_of::<T>() > mem::align_of::<*mut T>() {
-            // Need to unconditionally box values that don't match our
-            // alignment, even if sizeof(T) <= sizeof(Self)
+        if T::MUST_BOX {
```
Comment (RustyYato) [inline src/lib.rs]: As per the first comment, this code get's removed

File: src/lib.rs [hunk 8]
```diff
@@ -243,10 +352,11 @@ impl<T> Stowaway<T> {
...
 
-                        // under the current implementation of `ptr::write`, padding bytes are not always copied
-                        // this means that MIRI will see zeros where the paddings bytes are suppoed to be
-                        // and allows it. But this is *still* undefined behavior! So in order to make it easier
-                        // for MIRI to catch this behavior, we manually copy padding bytes
+                        // under the current implementation of `ptr::write`, padding bytes
+                        // are not always copied this means that MIRI will see zeros where
+                        // the paddings bytes are suppoed to be and allows it. But this is
+                        // *still* undefined behavior! So in order to make it easier for MIRI
+                        // to catch this behavior, we manually copy padding bytes
```
Comment (RustyYato) [inline src/lib.rs:361]: Can you link to the MIRI issue here?

File: src/lib.rs [hunk 9]
```diff
@@ -134,13 +137,130 @@
...
+    )*}
+}
+
+stowable_ptr! {
+    impl<T> for
+    Box<T> Option<Box<T>>
+    Rc<T> Option<Rc<T>>
+    RcWeak<T> Option<RcWeak<T>>
+    NonNull<T> Option<NonNull<T>>
+}
```
Comment (RustyYato) [inline src/lib.rs:225]: Why isn't `Arc` here? Also you can use a feature flag `alloc` to enable the `alloc` crate. This will allow you to use this crate on `no_std`.

The way I like to handle this is by doing:

```rust
#[cfg(all(not(feature = "std"), feature = "alloc"))]
extern crate alloc as std;
```
Then change all imports to use `core::` instead of `std::` except where `std` in necessary (for allocations or for `std` specific stuff)
You can also then gate all allocation related stuff on 
```rust
#[cfg(any(feature = "std", feature = "alloc"))]
```
But maybe for another PR.

**Review by RustyYato — CHANGES_REQUESTED** [review]
I don't think the `Stowable` trait should need `MUST_BOX`, it just complicates things for no real gain.

File: src/lib.rs [hunk 10]
```diff
@@ -275,6 +295,9 @@ use SizeClass::*;
 /// by boxing it or (if `T` is small enough) by packing it directly into the bytes
 /// of a raw pointer.
 ///
+/// Types stored in a `Stowaway` must implement [`Stowable`] in order to
+/// prevent unsound behavior related to uninitialized bytes.
+///
```
Comment (RustyYato) [inline src/lib.rs:280]: Link to #8 here

File: src/lib.rs (hunk 1 above)
Comment (Lucretiel) [reply src/lib.rs]: Oh; for some reason I had assumed you had a need to have `MaybeUninit` types in `Stowaway`. I'm definitely in favor of simplifying.

File: src/lib.rs (hunk 2 above)
Comment (Lucretiel) [reply src/lib.rs:231]: Yeah, I think we can detect that with https://github.com/dtolnay/rustversion and make it work without a feature flag. I definitely don't want to make the crate nightly-only, so I've left it as a TODO for now.

File: src/lib.rs (hunk 3 above)
Comment (Lucretiel) [reply src/lib.rs]: Whoops, good catch

File: src/lib.rs (hunk 6 above)
Comment (Lucretiel) [reply src/lib.rs:301]: There's an earlier draft of this project- I'm not sure if it's in the git history- where this does actually work, using a trait and an associated type, though I ended up getting rid of it because of the non-`Copy` restriction I mentioned.

File: src/lib.rs (hunk 9 above)
Comment (Lucretiel) [reply src/lib.rs:225]: Oh, for some reason I thought that `Arc` was std-only, because of atomic operations.

All the stuff you mentioned about an std feature is in this crate already, though I can get rid of it since right now `Arc` is the only thing it was being used for.

**Comment by Lucretiel** [comment]
Thanks for the comments; I'm happy to get rid of `MUST_BOX`. Will fix these tonight.

File: src/lib.rs (hunk 4 above)
Comment (Lucretiel) [reply src/lib.rs:262]: `Stowable` just means that the type can be stored in a `Stowaway`, not that it specifically will be packed instead of boxed.

File: src/lib.rs (hunk 9 above)
Comment (Lucretiel) [reply src/lib.rs:225]: Also, we can't put `alloc` behind a feature flag, because the standard operation of the library includes boxing larger types. We have to use it unconditionally.

**Comment by Lucretiel** [comment]
Edits completed

File: src/lib.rs (hunk 4 above)
Comment (RustyYato) [reply src/lib.rs:262]: Yes, Just a note about the documentation :)

File: src/lib.rs [hunk 11]
```diff
@@ -134,13 +137,129 @@
...
+
+// Pointers are obviously safe to stow. References are technically safe to
+// stow; the user must ensure that the lifetimes are correctly reconstructed
+// when calling from_raw.
+unsafe impl<T> Stowable for *const T {}
+unsafe impl<T> Stowable for *mut T {}
+unsafe impl<T> Stowable for &T {}
+unsafe impl<T> Stowable for Option<&mut T> {}
+unsafe impl<T> Stowable for Option<&T> {}
+unsafe impl<T> Stowable for &mut T {}
```
Comment (RustyYato) [inline src/lib.rs]: I missed this last time, these could take `T: ?Sized`

File: src/lib.rs (hunk 6 above)
Comment (RustyYato) [reply src/lib.rs:301]: Oh, I see. I think that would require const generics because you need to choose the layout based on the size and alignment, but that's a nice idea!

File: src/lib.rs [hunk 12]
```diff
@@ -134,13 +137,129 @@
...
+/// Correct usage of this trait is critical to stowaway's safety guarantees.
+/// This struct can only be implemented on types that can never have
+/// uninitialized bytes *anywhere* in their representation (including padding
+/// bytes). Making this determination isn't trivial, though typically it's
+/// safe if `sizeof(T) == sum(sizeof(fields in T))`, and all of the fields in
+/// `T` are themselves `Stowable`.
+///
+/// Structs which are `repr(transparent)` are `Stowable` if their inner field
+/// is `Stowable`.
+pub unsafe trait Stowable: Sized {}
```
Comment (RustyYato) [inline src/lib.rs]: I don't think we need to enforce `Sized` here, it prevents other people from using `Stowable` as a super-trait if they want dynamic dispatch, and `Stowaway` already requires `T: Sized` by default.

File: src/lib.rs [hunk 13]
```diff
@@ -134,13 +137,129 @@
...
+
+// TODO: determine when enums are safe to stow. For instance, is an
+// Option<usize> safe to stow? if the representation is IIIIIIII?UUUUUUU,
+// where I is the int part and ? is the discriminant, probably not.
+// At the very least, types where sizeof(Option<T>) == sizeof(T) are always
+// safe to stow as long as T is safe to stow.
```
Comment (RustyYato) [inline src/lib.rs:188]: `Option`'s representation is unspecified except for non-null optimization, so we can't say anything about it beyond that.

**Review by RustyYato — CHANGES_REQUESTED** [review]

**Comment by Lucretiel** [comment]
Sized changes added

**Comment by KrishnaSannasi** [comment]
LGTM

File: src/lib.rs [hunk 14]
```diff
@@ -173,36 +297,27 @@ use SizeClass::*;
...
             Zero
         } else if mem::size_of::<T>() <= mem::size_of::<*mut T>() {
             Packed
         } else {
             Boxed
         }
+        // Previously we checked the alignment of T, but the only way for
+        // alignof(T) > alignof(ptr) to be true is if
+        // sizeof(t) == 0 or sizeof(T) > sizeof(ptr), both of which are
+        // handled.
```
Comment (RustyYato) [inline src/lib.rs:320]: Is this documented somewhere? If not can you add this check because there shouldn't be any cost to doing so, const propogation should eliminate the check.

Comment (Lucretiel) [reply src/lib.rs:320]: Yup:
https://stackoverflow.com/questions/61256701/is-it-possible-to-have-a-type-with-a-larger-alignment-than-its-own-size
https://doc.rust-lang.org/reference/type-layout.html#size-and-alignment
> The size of a value is always a multiple of its alignment.

Comment (Lucretiel) [reply src/lib.rs:320]: I'm happy to restore it, but we require this property to be true in order for `[T; N]` to be stowable when `T: Stowable`, so I was happy to assume it here.

Comment (RustyYato) [reply src/lib.rs:320]: Ok, that works for me

**Comment by RustyYato** [comment]
This looks good to me
