### PR TITLE
Fix UB when T contains uninit bytes

### LINKED ISSUE #3: Undefined Behavior when T contains uninit bytes
Example: https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=d75fb532da27fbb22467a2b3b9439119

Use Tools -> Miri, it detects undefined behavior in Stowaway::new.

### PR DESCRIPTION
**Pull request by TyPR124**
Contains various tests for uninit bytes, and fixes #3. Does not fix UB when T is a ZST.

### CODE REVIEW

File: src/lib.rs [hunk 1]
```diff
@@ -217,15 +217,11 @@ impl<T> Stowaway<T> {
...
-                // If T smaller than *mut T, we need to initialize the extra
-                // bytes. TODO: figure out a way to initialize these bytes (to
-                // the satisfaction of defined behavior) without zeroing them,
-                // if possible.
-                let mut blob: MaybeUninit<*mut T> = if size_of::<T>() < size_of::<*mut T>() {
-                    MaybeUninit::zeroed()
-                } else {
-                    MaybeUninit::uninit()
-                };
+                // If T smaller than *mut T, or contains uninit bytes inernally,
```
Comment (Lucretiel) [inline src/lib.rs]: Propose changing this comment to something like "We need to zero all the bytes, because even if `sizeof(T)` == `sizeof(T*)`, there might still be "unused" and uninitialized padding bytes in the struct" or something similar

File: src/lib.rs [hunk 2]
```diff
@@ -320,6 +316,51 @@ impl<T> Stowaway<T> {
         storage as *mut ()
     }
 }
+// These tests should fail miri test
```
Comment (Lucretiel) [inline src/lib.rs]: Change to: "These tests detect undefined behavior in miri under naive, incorrect implementations of Stowaway" or something similar

**Review by Lucretiel — CHANGES_REQUESTED** [review]

**Comment by Lucretiel** [comment]
Looks good! Some minor comment update suggestions then I'll merge. Thank you for your discovery & work on this!

**Comment by TyPR124** [comment]
How does that look?

**Comment by Lucretiel** [comment]
Looks great, thank you!
